# Generated by Django 4.2.21 on 2025-06-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_total', models.FloatField()),
                ('price_subtotal', models.FloatField()),
                ('price_tax', models.FloatField()),
                ('Customer_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('Menu_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.menu')),
                ('Order_ID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='myapp.order')),
            ],
        ),
    ]
